// Generated by CoffeeScript 1.9.3
(function() {
  var Router;

  module.exports = Router = (function() {
    function Router(app, prefix) {
      this.app = app;
      this.prefix = prefix;
      if (this.prefix == null) {
        this.prefix = "";
      }
      this.routes = [];
    }

    Router.prototype.resources = function(name, controller, options) {
      var i, len, results, route, routes;
      routes = [
        [
          "get", "new", "/" + name + "/new", function() {
            return "/" + name + "/new";
          }
        ], [
          "post", "create", "/" + name, function() {
            return "/" + name;
          }
        ], [
          "get", "show", "/" + name + "/:id", function(id) {
            return "/" + name + "/" + id;
          }
        ], [
          "get", "index", "/" + name, function() {
            return "/" + name;
          }
        ], [
          "get", "edit", "/" + name + "/:id/edit", function(id) {
            return "/" + name + "/" + id + "/edit";
          }
        ], [
          "put", "update", "/" + name + "/:id", function(id) {
            return "/" + name + "/" + id + "?_method=PUT";
          }
        ], [
          "delete", "destroy", "/" + name + "/:id", function(id) {
            return "/" + name + "/" + id + "?_method=DELETE";
          }
        ]
      ];
      results = [];
      for (i = 0, len = routes.length; i < len; i++) {
        route = routes[i];
        if (typeof controller[route[1]] === "function") {
          results.push(this.addRoute(route[1] + "_" + name, route[0], route[2], routes[3], controller[route[1]]));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    Router.prototype.addRoute = function(alias, method, endpoint, adapter, middleware) {
      var base;
      if (this.app != null) {
        if ((base = this.app.locals).path == null) {
          base.path = {};
        }
        this.app.locals.path[alias] = endpoint;
        return this.app[method](endpoint, middleware);
      } else {
        return this.routes.push([alias, method, endpoint, adapter, middleware]);
      }
    };

    return Router;

  })();

}).call(this);
